apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibanocci
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector: 
    matchLabels:
      app: fibanocci
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fibanocci
        namespace: default
    spec:
      affinity: {}
      containers:
      - image: us-docker.pkg.dev/seventh-voltage-410418/first-repo/fibonocci:main
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        name: fibanocci
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
